package org.apache.turbine.fluxtest.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Nov 17 09:45:35 EST 2017]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class Author
    extends org.apache.turbine.fluxtest.om.BaseAuthor
{
    /** Serial version */
    private static final long serialVersionUID = 1510929935126L;



}
