package org.apache.turbine.fluxtest.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Nov 17 09:45:35 EST 2017]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class BookPeer
    extends org.apache.turbine.fluxtest.om.BaseBookPeer
{

}
