package org.apache.turbine.fluxtest.om;


/**
 * Maps ResultSet rows into TurbineUser objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Nov 17 09:45:35 EST 2017]
 *
 */
public class TurbineUserRecordMapper extends BaseTurbineUserRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1510929935924L;



}
