package org.apache.turbine.fluxtest.om;


/**
 * Maps ResultSet rows into TurbineRolePermission objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Nov 17 09:45:35 EST 2017]
 *
 */
public class TurbineRolePermissionRecordMapper extends BaseTurbineRolePermissionRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1510929935923L;



}
